name: Build EXE

on:
  # 推送到主分支时触发
  push:
    branches:
      - main
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller playwright
          pip install -r requirements.txt
          pip install PySimpleGUI-4.60.5-py3-none-any.whl  # 安装本地 whl 文件

      - name: Install Playwright Chromium
        run: |
          SET PLAYWRIGHT_BROWSERS_PATH=0
          playwright install chromium

      - name: Build EXE
        run: |
          pyinstaller -w main3.py

      - name: Compress build folder
        run: |
          Compress-Archive -Path D:\a\AutoUp\AutoUp\dist\main3 -DestinationPath D:\a\AutoUp\AutoUp\dist\main3.zip

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: main-exe-file
          path: D:\a\AutoUp\AutoUp\dist\main3.zip