name: Clear Artifact

on:
   workflow_dispatch:
jobs:
  clear:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - uses: geekyeggo/delete-artifact@v5
          with:
              name: main