name: Clear Artifact

on:
  workflow_dispatch:

jobs:
  clear:
    runs-on: windows-latest
    steps:
      - name: Delete Old Artifacts
        uses: actions/github-script@v6
        id: artifact
        with:
          script: |
            const res = await github.rest.actions.listArtifactsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            for (const artifact of res.data.artifacts) {
              await github.rest.actions.deleteArtifact({
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id,
              })
              console.log(`Deleted artifact with ID: ${artifact.id}`)
            }